site_name: CoordML Documentation

nav:
  - Home: 'index.md'
  - 'Quick Start':
    - 'Installation': './quick_start/installation.md'
  - 'CLI':
    - 'Installation': './cli/installation.md'
    - 'Basic Usage': './cli/basic_usage.md'
  - 'Sircle DSL':
    - 'Introduction to Sircle': './sircle_dsl/introduction.md'
    - 'Basics': './sircle_dsl/basics.md'
    - 'Prelude Functions': './sircle_dsl/prelude.md'
    - 'Formal Grammar': './sircle_dsl/grammar.md'
  - 'Central Server API':
    - 'Overview': './central_api/overview.md'
    - 'Worker Management API': './central_api/workers.md'
    - 'Experiment Management API': './central_api/experiments.md'
  - 'Runner Instance':
    - 'Overview': './runner_api/overview.md'
    - 'Runner Specification': './runner_api/spec.md'
    - 'Python Runner Usage': './runner_api/python_runner_usage.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs

plugins:
  - search

repo_url: https://github.com/CoordML

repo_name: CoordML

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
